server:
  port: 8080

#datasource configuration
spring:
  datasource:
    primary:
      username: root
      password: Ye#123456
      jdbc-url: jdbc:mysql://114.115.147.134:3306/situationAnalysis?allowMultiQueries=true&characterEncoding=utf8&useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
    secondary:
      username: root
      password: Ye#123456
      jdbc-url: jdbc:mysql://114.115.147.134:3306/vims30?allowMultiQueries=true&characterEncoding=utf8&useSSL=false
      driver-class-name: com.mysql.jdbc.Driver


#show sql log
logging:
  level:
    com:
      situation:
        analysis:
          mapper: debug
