server:
  port: 8199

#datasource configuration
spring:
  datasource:
    primary:
      username: root
      password: admin@123
      jdbc-url: jdbc:mysql://10.1.14.83:3306/situationAnalysis?serverTimezone=Asia/Shanghai&allowMultiQueries=true&characterEncoding=utf8&useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
    secondary:
      username: root
      password: admin@123
      jdbc-url: jdbc:mysql://10.1.14.83:3306/vims30?serverTimezone=Asia/Shanghai&allowMultiQueries=true&characterEncoding=utf8&useSSL=false
      driver-class-name: com.mysql.jdbc.Driver


#show sql log
logging:
  level:
    com:
      situation:
        analysis:
          mapper: debug
