server:
  port: 8080

#datasource configuration
spring:
  datasource:
    username: root
    password: Ye#123456
    url: jdbc:mysql://114.115.147.134:3306/monitor_system?allowMultiQueries=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver