spring:
  profiles:
    active: sit



#pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql



##mybatis
#mybatis:
#  mapper-locations: classpath:mapping/*.xml
#  #指定entity路径以后，可以在mapper里面用类名作为参数，而不必指定全路径的类名
#  type-aliases-package: com.situation.analysis.entity
