
package com.situation.analysis.webservices.expenses;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SearchExpensesService", targetNamespace = "http://service.webservice.invoice.app.eweaver.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SearchExpensesService {


    /**
     * 
     * @param hrmno
     * @return
     *     returns com.situation.analysis.webservices.expenses.ExpensesResult
     */
    @WebMethod(action = "searchExpenses")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchExpenses", targetNamespace = "http://service.webservice.invoice.app.eweaver.com/", className = "com.situation.analysis.webservices.expenses.SearchExpenses")
    @ResponseWrapper(localName = "searchExpensesResponse", targetNamespace = "http://service.webservice.invoice.app.eweaver.com/", className = "com.situation.analysis.webservices.expenses.SearchExpensesResponse")
    public ExpensesResult searchExpenses(
        @WebParam(name = "HRMNO", targetNamespace = "")
        String hrmno);

}
