
package com.situation.analysis.webservices.expenses;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SearchExpensesServiceImplService", targetNamespace = "http://service.webservice.invoice.app.eweaver.com/", wsdlLocation = "http://10.50.57.88:8095/ws/SearchExpensesService?wsdl")
public class SearchExpensesServiceImplService
    extends Service
{

    private final static URL SEARCHEXPENSESSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SEARCHEXPENSESSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName SEARCHEXPENSESSERVICEIMPLSERVICE_QNAME = new QName("http://service.webservice.invoice.app.eweaver.com/", "SearchExpensesServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.50.57.88:8095/ws/SearchExpensesService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SEARCHEXPENSESSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        SEARCHEXPENSESSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public SearchExpensesServiceImplService() {
        super(__getWsdlLocation(), SEARCHEXPENSESSERVICEIMPLSERVICE_QNAME);
    }

    public SearchExpensesServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SEARCHEXPENSESSERVICEIMPLSERVICE_QNAME, features);
    }

    public SearchExpensesServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SEARCHEXPENSESSERVICEIMPLSERVICE_QNAME);
    }

    public SearchExpensesServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SEARCHEXPENSESSERVICEIMPLSERVICE_QNAME, features);
    }

    public SearchExpensesServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SearchExpensesServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SearchExpensesService
     */
    @WebEndpoint(name = "SearchExpensesServiceImplPort")
    public SearchExpensesService getSearchExpensesServiceImplPort() {
        return super.getPort(new QName("http://service.webservice.invoice.app.eweaver.com/", "SearchExpensesServiceImplPort"), SearchExpensesService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SearchExpensesService
     */
    @WebEndpoint(name = "SearchExpensesServiceImplPort")
    public SearchExpensesService getSearchExpensesServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.webservice.invoice.app.eweaver.com/", "SearchExpensesServiceImplPort"), SearchExpensesService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SEARCHEXPENSESSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw SEARCHEXPENSESSERVICEIMPLSERVICE_EXCEPTION;
        }
        return SEARCHEXPENSESSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
