
package com.situation.analysis.webservices.expenseinfo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ReadExpenseinfoServiceImplService", targetNamespace = "http://service.webservice.invoice.app.eweaver.com/", wsdlLocation = "http://10.50.57.88:8095/ws/ReadExpenseinfoService?wsdl")
public class ReadExpenseinfoServiceImplService
    extends Service
{

    private final static URL READEXPENSEINFOSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException READEXPENSEINFOSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName READEXPENSEINFOSERVICEIMPLSERVICE_QNAME = new QName("http://service.webservice.invoice.app.eweaver.com/", "ReadExpenseinfoServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.50.57.88:8095/ws/ReadExpenseinfoService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        READEXPENSEINFOSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        READEXPENSEINFOSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public ReadExpenseinfoServiceImplService() {
        super(__getWsdlLocation(), READEXPENSEINFOSERVICEIMPLSERVICE_QNAME);
    }

    public ReadExpenseinfoServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), READEXPENSEINFOSERVICEIMPLSERVICE_QNAME, features);
    }

    public ReadExpenseinfoServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, READEXPENSEINFOSERVICEIMPLSERVICE_QNAME);
    }

    public ReadExpenseinfoServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, READEXPENSEINFOSERVICEIMPLSERVICE_QNAME, features);
    }

    public ReadExpenseinfoServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReadExpenseinfoServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ReadExpenseinfoService
     */
    @WebEndpoint(name = "ReadExpenseinfoServiceImplPort")
    public ReadExpenseinfoService getReadExpenseinfoServiceImplPort() {
        return super.getPort(new QName("http://service.webservice.invoice.app.eweaver.com/", "ReadExpenseinfoServiceImplPort"), ReadExpenseinfoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReadExpenseinfoService
     */
    @WebEndpoint(name = "ReadExpenseinfoServiceImplPort")
    public ReadExpenseinfoService getReadExpenseinfoServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.webservice.invoice.app.eweaver.com/", "ReadExpenseinfoServiceImplPort"), ReadExpenseinfoService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (READEXPENSEINFOSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw READEXPENSEINFOSERVICEIMPLSERVICE_EXCEPTION;
        }
        return READEXPENSEINFOSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
