
package com.situation.analysis.webservices.expenseinfo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ReadExpenseinfoService", targetNamespace = "http://service.webservice.invoice.app.eweaver.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReadExpenseinfoService {


    /**
     * 
     * @param hrmno
     * @param billno
     * @param sid
     * @return
     *     returns com.situation.analysis.webservices.expenseinfo.ReadExpenseinfoResult
     */
    @WebMethod(action = "searchExpenses")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readExpenseinfo", targetNamespace = "http://service.webservice.invoice.app.eweaver.com/", className = "com.situation.analysis.webservices.expenseinfo.ReadExpenseinfo")
    @ResponseWrapper(localName = "readExpenseinfoResponse", targetNamespace = "http://service.webservice.invoice.app.eweaver.com/", className = "com.situation.analysis.webservices.expenseinfo.ReadExpenseinfoResponse")
    public ReadExpenseinfoResult readExpenseinfo(
        @WebParam(name = "SID", targetNamespace = "")
        String sid,
        @WebParam(name = "BILLNO", targetNamespace = "")
        String billno,
        @WebParam(name = "HRMNO", targetNamespace = "")
        String hrmno);

}
