
package com.situation.analysis.webservices.error;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SendExpenseErrorServiceImplService", targetNamespace = "http://service.webservice.invoice.app.eweaver.com/", wsdlLocation = "http://10.50.57.88:8095/ws/SendExpenseErrorService?wsdl")
public class SendExpenseErrorServiceImplService
    extends Service
{

    private final static URL SENDEXPENSEERRORSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SENDEXPENSEERRORSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName SENDEXPENSEERRORSERVICEIMPLSERVICE_QNAME = new QName("http://service.webservice.invoice.app.eweaver.com/", "SendExpenseErrorServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.50.57.88:8095/ws/SendExpenseErrorService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SENDEXPENSEERRORSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        SENDEXPENSEERRORSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public SendExpenseErrorServiceImplService() {
        super(__getWsdlLocation(), SENDEXPENSEERRORSERVICEIMPLSERVICE_QNAME);
    }

    public SendExpenseErrorServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SENDEXPENSEERRORSERVICEIMPLSERVICE_QNAME, features);
    }

    public SendExpenseErrorServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SENDEXPENSEERRORSERVICEIMPLSERVICE_QNAME);
    }

    public SendExpenseErrorServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SENDEXPENSEERRORSERVICEIMPLSERVICE_QNAME, features);
    }

    public SendExpenseErrorServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SendExpenseErrorServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SendExpenseErrorService
     */
    @WebEndpoint(name = "SendExpenseErrorServiceImplPort")
    public SendExpenseErrorService getSendExpenseErrorServiceImplPort() {
        return super.getPort(new QName("http://service.webservice.invoice.app.eweaver.com/", "SendExpenseErrorServiceImplPort"), SendExpenseErrorService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SendExpenseErrorService
     */
    @WebEndpoint(name = "SendExpenseErrorServiceImplPort")
    public SendExpenseErrorService getSendExpenseErrorServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.webservice.invoice.app.eweaver.com/", "SendExpenseErrorServiceImplPort"), SendExpenseErrorService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SENDEXPENSEERRORSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw SENDEXPENSEERRORSERVICEIMPLSERVICE_EXCEPTION;
        }
        return SENDEXPENSEERRORSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
