
package com.situation.analysis.webservices.error;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SendExpenseErrorService", targetNamespace = "http://service.webservice.invoice.app.eweaver.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SendExpenseErrorService {


    /**
     * 
     * @param cehckstatus
     * @param atDATA
     * @param errornum
     * @param col4
     * @param hrmno
     * @param col5
     * @param col2
     * @param billno
     * @param col3
     * @param sid
     * @param col1
     * @return
     *     returns com.situation.analysis.webservices.error.SendExpenseResult
     */
    @WebMethod(action = "sendExpenseError")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendExpenseError", targetNamespace = "http://service.webservice.invoice.app.eweaver.com/", className = "com.situation.analysis.webservices.error.SendExpenseError")
    @ResponseWrapper(localName = "sendExpenseErrorResponse", targetNamespace = "http://service.webservice.invoice.app.eweaver.com/", className = "com.situation.analysis.webservices.error.SendExpenseErrorResponse")
    public SendExpenseResult sendExpenseError(
        @WebParam(name = "SID", targetNamespace = "")
        String sid,
        @WebParam(name = "BILLNO", targetNamespace = "")
        String billno,
        @WebParam(name = "HRMNO", targetNamespace = "")
        String hrmno,
        @WebParam(name = "ERRORNUM", targetNamespace = "")
        int errornum,
        @WebParam(name = "CEHCKSTATUS", targetNamespace = "")
        int cehckstatus,
        @WebParam(name = "COL1", targetNamespace = "")
        String col1,
        @WebParam(name = "COL2", targetNamespace = "")
        String col2,
        @WebParam(name = "COL3", targetNamespace = "")
        String col3,
        @WebParam(name = "COL4", targetNamespace = "")
        String col4,
        @WebParam(name = "COL5", targetNamespace = "")
        String col5,
        @WebParam(name = "AT_DATA", targetNamespace = "")
        List<InvoiceException> atDATA);

}
